name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [7.3, 7.4, "8.0", 8.1]
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: "Build Version Change"
        run: |
          export VERSION=${{ matrix.version }}
          envsubst '$VERSION' < Dockerfile.tpl | tee Dockerfile

      - name: Build image
        run: |
          export IMAGE_NAME=ci_php:${{ matrix.version }}
          docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push image
        run: |
          export IMAGE_NAME=ci_php:${{ matrix.version }}
          export IMAGE_ID=ghcr.io/luckyraul/php:${{ matrix.version }}-ci

          # Change all uppercase to lowercase
          export IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo $IMAGE_ID

          docker tag $IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID
